server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
#          uri: file:C:\Users\Enis Halilaj\Desktop\twitterv2\config-server-repository
          uri: file://Users/alimhtsai/Documents/ucimswe/6_side_project/Event_driven_microservices/config-server-repository
          clone-on-start: true
    fail-fast: true